version: '3'

services:
  scheduling.api:
    image: scheduling.api
    build:
      context: ./src/Services/Scheduling/Skej.Scheduling.API
      dockerfile: Dockerfile

  skej.spa:
    image: skej.spa
    build:
      context: ./src/Web/Skej.SPA
      dockerfile: Dockerfile
