version: '3'

services:
  skej.scheduling.api:
    image: skej.scheduling.api
    build:
      context: ./Scheduling/Skej.Scheduling.API
      dockerfile: Dockerfile

  skej.spa:
    image: skej.spa
    build:
      context: ./Web/Skej.SPA
      dockerfile: Dockerfile
